version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      RAILS_ENV: development
    stdin_open: true
    tty: true
    command: bash -c "
      wait-for-it.sh db:5432 -- rm -f tmp/pids/server.pid &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed &&
      rails server -b '0.0.0.0'"

volumes:
  db_data:
